import { test, expect } from '@playwright/test'
import { fixturePng } from '../media-server.mjs'

const editor = page => page.locator('#toolbar-editor')
const action = (page, id) => page.locator(`[data-command="${id}"]`)
async function mount(page, a = 0, b = 5) {
  await page.goto('/toolbar')
  await page.waitForFunction(() => window.ready)
  await editor(page).focus()
  await page.evaluate(([a, b]) => window.toolbar.select(a, b), [a, b])
}
async function link(page) {
  await action(page, 'link').click()
  await expect(page.getByRole('dialog')).toBeVisible()
}
test.afterEach(async ({ page }) => page.evaluate(() => window.toolbar?.dispose()).catch(() => {}))

test('named toolbar exposes pressed and disabled states and a single Tab stop', async ({ page }, testInfo) => {
  await mount(page)
  await expect(page.getByRole('toolbar', { name: 'Text bearbeiten' })).toBeVisible()
  await expect(action(page, 'bold')).toHaveAccessibleName('Fett')
  await expect(action(page, 'bold')).toHaveAttribute('aria-pressed', 'false')
  await expect(action(page, 'undo')).toBeDisabled()
  await expect(action(page, 'redo')).toBeDisabled()
  await expect(page.locator('[role="toolbar"] button[tabindex="0"]')).toHaveCount(1)
  await expect(editor(page)).toHaveAccessibleName('Dokument')
  await page.screenshot({ path: testInfo.outputPath('toolbar.png'), fullPage: true })
})

test('toolbar and modal remain usable on a narrow viewport', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await mount(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await link(page)
  await expect(page.getByLabel('Adresse', { exact: true })).toBeFocused()
  const box = await page.getByRole('dialog').boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('dialog-narrow.png'), fullPage: true })
})

test('mouse formatting retains editor focus and the selected text', async ({ page }) => {
  await mount(page)
  await action(page, 'bold').click()
  await expect(editor(page)).toBeFocused()
  await expect(editor(page).locator('strong')).toHaveText('Hello')
  await expect(action(page, 'bold')).toHaveAttribute('aria-pressed', 'true')
  await expect(action(page, 'undo')).toBeEnabled()
  await action(page, 'undo').click()
  await expect(editor(page).locator('strong')).toHaveCount(0)
  await expect(action(page, 'redo')).toBeEnabled()
})

test('Tab leaves the editor; arrows skip disabled actions; Space retains toolbar focus', async ({ page }) => {
  await mount(page)
  await page.keyboard.press('Tab')
  await expect(action(page, 'bold')).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(action(page, 'italic')).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(action(page, 'link')).toBeFocused()
  await page.keyboard.press('Home')
  await page.keyboard.press('Space')
  await expect(action(page, 'bold')).toBeFocused()
  await expect(editor(page).locator('strong')).toHaveText('Hello')
  await page.keyboard.press('End')
  await expect(action(page, 'image')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('#readonly')).toBeFocused()
})

test('stored marks at a collapsed caret are visible and affect subsequent typing', async ({ page }) => {
  await mount(page, 2, 2)
  await action(page, 'bold').click()
  await expect(action(page, 'bold')).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.type('X')
  await expect(editor(page).locator('strong')).toHaveText('X')
  expect(await page.evaluate(() => window.toolbar.text())).toBe('HeXllo world')
})

test('a partially formatted selection reports mixed state', async ({ page }) => {
  await mount(page)
  await action(page, 'bold').click()
  await page.evaluate(() => window.toolbar.select(0, 6))
  await expect(action(page, 'bold')).toHaveAttribute('aria-pressed', 'mixed')
})

test('mouse dialog moves focus into a named modal and Escape restores editor selection', async ({ page }) => {
  await mount(page, 5, 0)
  await link(page)
  await expect(page.getByRole('dialog')).toHaveAccessibleName('Link bearbeiten')
  await expect(page.getByLabel('Adresse', { exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Abbrechen' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Adresse', { exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(editor(page)).toBeFocused()
  expect(await page.evaluate(() => window.getSelection().toString())).toBe('Hello')
  expect(await page.evaluate(() => window.toolbar.text())).toBe('Hello world')
})

test('keyboard dialog activation returns focus to the invoking toolbar button', async ({ page }) => {
  await mount(page)
  await action(page, 'link').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Adresse', { exact: true })).toBeFocused()
  await page.getByLabel('Adresse', { exact: true }).fill('/linked')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(action(page, 'link')).toBeFocused()
  await expect(editor(page).locator('a')).toHaveText('Hello')
})

test('link validation retains the dialog and source, then maps both endpoints through background edits', async ({ page }) => {
  await mount(page)
  await link(page)
  await page.getByLabel('Adresse', { exact: true }).fill('javascript:bad')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(page.getByRole('alert')).not.toBeEmpty()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => window.toolbar.text())).toBe('Hello world')
  await page.getByLabel('Adresse', { exact: true }).focus()
  await page.evaluate(() => window.toolbar.edit())
  await expect(page.getByLabel('Adresse', { exact: true })).toBeFocused()
  await page.getByLabel('Adresse', { exact: true }).fill('/mapped')
  await page.getByLabel('Titel', { exact: true }).fill('Mapped title')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(editor(page).locator('a')).toHaveAttribute('href', '/mapped')
  await expect(editor(page).locator('a')).toHaveAttribute('title', 'Mapped title')
  expect(await page.evaluate(() => window.toolbar.text())).toBe('XHello world')
  expect(await page.evaluate(() => window.toolbar.undo())).toBe(true)
  await expect(editor(page).locator('a')).toHaveCount(0)
  expect(await page.evaluate(() => window.toolbar.text())).toBe('XHello world')
})

test('existing links can be retargeted and removed without deleting text', async ({ page }) => {
  await mount(page)
  await link(page)
  await page.getByLabel('Adresse', { exact: true }).fill('/first')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await link(page)
  await expect(page.getByLabel('Adresse', { exact: true })).toHaveValue('/first')
  await page.getByLabel('Adresse', { exact: true }).fill('/second')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(editor(page).locator('a')).toHaveAttribute('href', '/second')
  await link(page)
  await page.getByRole('button', { name: 'Link entfernen' }).click()
  await expect(editor(page).locator('a')).toHaveCount(0)
  expect(await page.evaluate(() => window.toolbar.text())).toBe('Hello world')
})

for (const kind of ['removed', 'expired', 'replaced', 'history', 'invalidated']) {
  test(`${kind} dialog target cannot insert into a fallback position`, async ({ page }) => {
    await mount(page)
    if (kind === 'replaced' || kind === 'history') await page.evaluate(() => window.toolbar.edit())
    await link(page)
    await page.evaluate(kind => {
      if (kind === 'removed') window.toolbar.removeTarget()
      if (kind === 'expired') window.toolbar.edit(80)
      if (kind === 'replaced') window.toolbar.replaceDocument()
      if (kind === 'history') window.toolbar.undo()
      if (kind === 'invalidated') window.toolbar.invalidate()
    }, kind)
    const before = await page.evaluate(() => window.toolbar.text())
    await page.getByLabel('Adresse', { exact: true }).fill('/invalid-target')
    await page.getByRole('button', { name: 'Übernehmen' }).click()
    await expect(page.getByRole('alert')).not.toBeEmpty()
    await expect(editor(page).locator('a')).toHaveCount(0)
    expect(await page.evaluate(() => window.toolbar.text())).toBe(before)
  })
}

test('image dialog accepts an empty alt, replaces the range atomically and supports Undo', async ({ page }) => {
  await mount(page)
  await action(page, 'image').click()
  await page.getByLabel('Bildadresse', { exact: true }).fill('/media/assets/fixture.png')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(editor(page).locator('img')).toHaveAttribute('alt', '')
  expect(await page.evaluate(() => window.toolbar.text())).toBe(' world')
  await expect(editor(page)).toBeFocused()
  await action(page, 'undo').click()
  expect(await page.evaluate(() => window.toolbar.text())).toBe('Hello world')
})

test('application file callback uses the actual chooser and P26 multipart service', async ({ page }) => {
  await mount(page)
  await action(page, 'image').click()
  await page.getByLabel('Alternativtext', { exact: false }).fill('Uploaded picture')
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Datei auswählen' }).click()
  await (await chooser).setFiles({ name: 'image.png', mimeType: 'image/png', buffer: fixturePng })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(editor(page).locator('img')).toHaveAttribute('alt', 'Uploaded picture')
  await expect(editor(page).locator('img')).toHaveAttribute('src', /\/media\/assets\/[a-f0-9]{64}\.png/)
  await expect(page.getByRole('status')).toHaveText('Bild eingefügt.')
})

test('an existing image exposes its alt and can be made decorative without reinserting it', async ({ page }) => {
  await mount(page, 2, 2)
  await action(page, 'image').click()
  await page.getByLabel('Bildadresse', { exact: true }).fill('/media/assets/fixture.png')
  await page.getByLabel('Alternativtext', { exact: false }).fill('Before')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  const before = await editor(page).locator('img').evaluate(el => el.outerHTML)
  await page.evaluate(() => window.toolbar.selectImage())
  await action(page, 'image').click()
  await expect(page.getByRole('dialog')).toHaveAccessibleName('Bild bearbeiten')
  await expect(page.getByLabel('Alternativtext', { exact: false })).toHaveValue('Before')
  await page.getByLabel('Alternativtext', { exact: false }).fill('')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(editor(page).locator('img')).toHaveAttribute('alt', '')
  await expect(editor(page).locator('img')).toHaveCount(1)
  expect(await page.evaluate(() => window.toolbar.undo())).toBe(true)
  expect(await editor(page).locator('img').evaluate(el => el.outerHTML)).toBe(before)
})

test('composition availability disables and re-enables toolbar actions', async ({ page }) => {
  await mount(page, 2, 2)
  await page.evaluate(() => document.getElementById('toolbar-editor').dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true })))
  await expect(action(page, 'bold')).toBeDisabled()
  await expect(action(page, 'image')).toBeDisabled()
  await page.evaluate(() => document.getElementById('toolbar-editor').dispatchEvent(new CompositionEvent('compositionend', { bubbles: true })))
  await expect(action(page, 'bold')).toBeEnabled()
  await expect(action(page, 'image')).toBeEnabled()
})

test('readonly disables commands and rejects an already-open dialog', async ({ page }) => {
  await mount(page)
  await link(page)
  await page.evaluate(() => window.toolbar.readonly(true))
  await page.getByLabel('Adresse', { exact: true }).fill('/readonly')
  await page.getByRole('button', { name: 'Übernehmen' }).click()
  await expect(page.getByRole('alert')).toContainText('nicht bearbeitbar')
  await page.getByRole('button', { name: 'Abbrechen' }).click()
  for (const id of ['bold', 'italic', 'undo', 'redo', 'link', 'image']) await expect(action(page, id)).toBeDisabled()
  expect(await page.evaluate(() => window.toolbar.openLink())).toBe(false)
  expect(await page.evaluate(() => window.toolbar.text())).toBe('Hello world')
})

test('background changes never steal an external input focus', async ({ page }) => {
  await mount(page)
  await page.locator('#outside').fill('keep focus')
  await page.evaluate(() => window.toolbar.edit())
  await expect(page.locator('#outside')).toBeFocused()
  await expect(page.locator('#outside')).toHaveValue('keep focus')
})

test('disposing an open dialog removes its modal and all toolbar controls', async ({ page }) => {
  await mount(page)
  await link(page)
  await page.evaluate(() => window.toolbar.dispose())
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('toolbar')).toHaveCount(0)
  await page.locator('#outside').fill('available again')
  await expect(page.locator('#outside')).toBeFocused()
})

test('forced colors and reduced motion retain visible focus and pressed indication', async ({ page }) => {
  await page.emulateMedia({ forcedColors: 'active', reducedMotion: 'reduce' })
  await mount(page)
  await action(page, 'bold').focus()
  await page.keyboard.press('Space')
  const styles = await action(page, 'bold').evaluate(el => {
    const s = getComputedStyle(el)
    return { outline: s.outlineStyle, width: s.outlineWidth, border: s.borderTopWidth,
      transition: s.transitionDuration, decoration: s.textDecorationLine }
  })
  expect(styles.outline).not.toBe('none')
  expect(styles.width).toBe('3px')
  expect(styles.border).toBe('3px')
  expect(styles.decoration).toContain('underline')
  expect(styles.transition).toBe('0s')
})
